### ISSUE TITLE
Bug: Search does not work

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-py#102]
Try to search for strings or IDs in the top-right search window of OMERO.web.

```  

        Traceback (most recent call last):

  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)

  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)

  File "/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/omero/workspace/OMERO-web/OMERO.web/lib/python/omeroweb/decorators.py", line 485, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/omero/workspace/OMERO-web/OMERO.web/lib/python/omeroweb/decorators.py", line 535, in wrapper
    context = f(request, *args, **kwargs)

  File "/home/omero/workspace/OMERO-web/OMERO.web/lib/python/omeroweb/webclient/views.py", line 498, in load_template
    url=url, **kwargs)

  File "/home/omero/workspace/OMERO-web/OMERO.web/lib/python/omeroweb/webclient/views.py", line 470, in _load_template
    myColleagues.sort(key=lambda x: x.getLastName().lower())

AttributeError: 'dict_values' object has no attribute 'sort'

<WSGIRequest: GET '/web/webclient/search/?search_query=9665'>
 
```

**Comment by will-moore** [comment]
Fixed at https://github.com/ome/omero-web/pull/48
