### ISSUE TITLE
Bug: Import on non-default ports

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-py#103]
connecting to a port 44064 fails on CLI with 

```
2019-11-04 15:40:22,450 1199       [      main] ERROR  formats.importer.cli.CommandLineImporter - Error during import process.
Glacier2.PermissionDeniedException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_222]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_222]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_222]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_222]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_222]
	at IceInternal.BasicStream.createUserException(BasicStream.java:2779) ~[ice.jar:na]
	at IceInternal.BasicStream.access$300(BasicStream.java:14) ~[ice.jar:na]
	at IceInternal.BasicStream$EncapsDecoder11.throwException(BasicStream.java:3614) ~[ice.jar:na]
	at IceInternal.BasicStream.throwException(BasicStream.java:2291) ~[ice.jar:na]
	at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399) ~[ice.jar:na]
	at Glacier2.RouterPrxHelper.end_createSession(RouterPrxHelper.java:178) ~[glacier2.jar:na]
	at Glacier2.RouterPrxHelper.createSession(RouterPrxHelper.java:49) ~[glacier2.jar:na]
	at Glacier2.RouterPrxHelper.createSession(RouterPrxHelper.java:41) ~[glacier2.jar:na]
	at omero.client.createSession(client.java:810) ~[omero-blitz.jar:5.5.3]
	at omero.client.joinSession(client.java:744) ~[omero-blitz.jar:5.5.3]
	at omero.client.createClient(client.java:543) ~[omero-blitz.jar:5.5.3]
	at ome.formats.OMEROMetadataStoreClient.unsecure(OMEROMetadataStoreClient.java:743) ~[omero-blitz.jar:5.5.3]
	at ome.formats.OMEROMetadataStoreClient.initialize(OMEROMetadataStoreClient.java:703) ~[omero-blitz.jar:5.5.3]
	at ome.formats.importer.ImportConfig.createStore(ImportConfig.java:379) ~[omero-blitz.jar:5.5.3]
	at ome.formats.importer.cli.CommandLineImporter.<init>(CommandLineImporter.java:162) ~[omero-blitz.jar:5.5.3]
	at ome.formats.importer.cli.CommandLineImporter.main(CommandLineImporter.java:989) ~[omero-blitz.jar:5.5.3]
```

cc @joshmoore @jburel

**Comment by pwalczysko** [comment]
Note also https://github.com/ome/omero-insight/issues/90

**Comment by pwalczysko** [comment]
note that unlike for insight, where the connection fails, for CLI, the connection is successful

```
Previous session expired for root on idr1-slot2.openmicroscopy.org:44064
Server: [idr1-slot2.openmicroscopy.org:44064]
Username: [root]
Password:
Created session for root@idr1-slot2.openmicroscopy.org:44064. Idle timeout: 10 min. Current group: system
(omero) pwalczysko@ls31618~/local-server/OMERO.server-5.5.1-ice36-b122$ 
```

**Comment by manics** [comment]
Is this still a problem?

**Comment by joshmoore** [comment]
I wouldn't think it's been fixed.

**Comment by pwalczysko** [comment]
> I wouldn't think it's been fixed.
Ditto, no indication of a fix afaik

**Comment by sbesson** [comment]
As demonstrated  in https://github.com/ome/omero-py/issues/103#issuecomment-549478567, the original issue is not the OMERO connection via the SSL port but the creation of an unencrypted session using the server TCP port during the import process.

I tried to reproduce this issue using a locally modified version of https://github.com/ome/docker-example-omero

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 9e3c9c6..3a0634b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -22,12 +22,14 @@ services:
       CONFIG_omero_db_user: omero
       CONFIG_omero_db_pass: omero
       CONFIG_omero_db_name: omero
+      CONFIG_omero_ports_prefix: 1
       ROOTPASS: omero
     networks:
       - omero
     ports:
-      - "4063:4063"
-      - "4064:4064"
+      - "14063:14063"
+      - "14064:14064"
     volumes:
       - "omero:/OMERO"
     ulimits:
```

`omero import test.fake -s localhost -u root -p 14064` was successful both within and outside the container.

Also not exposing port 14063 and only leaving the SSL port exposed externally does not suffice to create a failing scenario. Under this this circumstances, the importer client fails to create an encrypted session and falls back to the encrypted session to resume the import process.

We probably need more information about a minimal configuration allowing to reproduce the error above.
