### ISSUE TITLE
omero script error output is shown as bytes

### ISSUE THREAD

**Issue by manics** [ome/omero-py#155]
```
$ omero script launch script-with-error.py IDs=2016
Using session for ...
Job 10810 ready
Waiting....
Callback received: FINISHED

        *** start stderr (id=10563)***
        * b'Traceback (most recent call last):\n  File "./script", line 78, in <module>\n    run_script()\n  File "./script", line 70, in run_script\n    file_anns, message = process_images(conn, script_params)\n  File "./script", line 28, in process_images\n    f.write(text)\nTypeError: write() argument must be str, not list\n'
        *** end stderr ***


        *** out parameters ***
        ***  done ***
```

**Comment by sbesson** [comment]
Fixed by https://github.com/ome/omero-py/pull/310
