### ISSUE TITLE
Omero seems to require a HOME directory

### ISSUE THREAD

**Issue by bgruening** [ome/omero-py#178]
Running Omero in a Container yields this error. I assume Omero needs to have a HOME environment set, which is can not be assumed on HPC environments.
```
Invalid tmp dir: /omero/tmp
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/omero/util/temp_files.py", line 178, in tmpdir
    self.create(target)
  File "/usr/local/lib/python3.8/site-packages/omero/util/temp_files.py", line 246, in create
    dir.makedirs(0o700)
  File "/usr/local/lib/python3.8/site-packages/omero_ext/path.py", line 1254, in makedirs
    os.makedirs(self, mode)
  File "/usr/local/lib/python3.8/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/omero'
```

**Comment by joshmoore** [comment]
Hi @bgruening,

you can override the location that's being attempted by setting `OMERO_USERDIR`. Is there a directory that it would be safe to fallback to in your case?

~Josh

**Comment by bgruening** [comment]
Hi Josh,

in Galaxy we simply can set the HOME dir to a temp dir, thats what I did in the end. But in general, I don't think its a good idea to assume such a directory. There should be a fallback to some $TEMP or a similar mechanism, imho.

HPC environments can be tricky and they are so diverse, we have collected a few of those HPC recommendations in this article, maybe its interesting: [10.1093/gigascience/giz054](https://academic.oup.com/gigascience/article/8/5/giz054/5497810)

Ciao,
Bjoern

**Comment by jburel** [comment]
Thanks @bgruening for the report, falling back to something like ``/tmp/omero`` should be doable.

**Comment by manics** [comment]
@bgruening we've [got a proposal](https://github.com/ome/omero-py/issues/210#issuecomment-652919168) to defer to https://pypi.org/project/appdirs/ for managing user runtime directories. Would this work?

**Comment by bgruening** [comment]
@manics probably. But keep in mind that a fallback is needed, because you can not assume a HOME directory at all.

**Comment by davelopez** [comment]
Hi!
Recently, we integrated a file source in Galaxy that uses omero-py to browse and download images for analysis, but we noticed that there is a side-effect when importing omero-py that assumes the default directory for temporary files is inside the User's home directory https://github.com/galaxyproject/galaxy/issues/22203
Unfortunately, we cannot set OMERO_TMPDIR before Galaxy loads the plugin because this will require every Galaxy admin to know and set that environment variable, usually in a complex HPC environment, as Björn mentioned. So we did a workaround to defer the import until we have the appropriate configured path for temp files, and then set the environment variable.
It would be nice to have the default to `tempfile.gettempdir()` or something similar that does not use the user's home directory, so I thought it might be related to this issue.
Thanks for considering it!

**Comment by will-moore** [comment]
@davelopez it looks like your issue would be fixed by the removal of this line:
https://github.com/ome/omero-py/blob/927ca61a4534ac265f32b6827194dfc9a323a887/src/omero/util/temp_files.py#L152

Then, the `targets` list would only contain the `tempfile.gettempdir() / "omero" / "tmp"` dir and that would get used instead of the user's `omero` dir.

The logic of using the user's home directory in preference to the tempdir was originally added back in https://github.com/ome/omero-py/commit/7db67b1dcb7689b174dae7d60bac09006243d7a9
but I don't know if that behaviour is particularly important @joshmoore, or if it would be safe to simply use tempdir instead?

**Comment by will-moore** [comment]
@sbesson Do you have an idea for a nice solution to this that would be acceptable to users who are happy with the current behaviour? Could it be configurable or could we test for `OMERO_TMPDIR` being set?

**Comment by sbesson** [comment]
The current logic of `omero.util.temp_files.tmpdir()` is to construct a series of candidate folders using the following order of precedence
 1. `OMERO_TMPDIR`
 2. `get_omero_userdir()`
 3. `tempfile.gettempdir()`
and select the first folder in that list that meets certain criteria, currently being able to create a directory with a lock.

I would not change this order without a deeper understanding of the impact on all deployment scenarios than what has been discussed so far. As an example, we are increasingly seeing situations where the `/tmp` directory which is typically the target of `tempfile.gettempdir()`is hardened or constrained.

`OMERO_TMPDIR` should  provide full control for the user. If setting this variable is not desired or possible, what would be the criteria or checks under which `get_omero_userdir()` would be excluded from the candidate list in the spirit of https://github.com/ome/omero-py/issues/178#issuecomment-4221353220?

**Comment by davelopez** [comment]
Thanks for the discussion so far.

To clarify our specific use case: it appears the current implementation creates the temporary folders (using the mentioned order of precedence) as a **side-effect of the initial module import**. The issue for us is not the order, but the time at which this decision is taken.

This is a challenge for us because we often don't have the final directory information available until the moment we are ready to instantiate the `BlitzGateway`. Currently, we have worked around this by using a lazy import of the library right before instantiation, but this feels like a suboptimal pattern.

Would it be possible to move the directory creation logic out of the top-level import and into the instantiation process? 

Alternatively, allowing the temp path to be passed as an optional parameter during initialization would also solve the issue. We’d love to hear your thoughts on whether a more 'lazy' approach to these directories is feasible.
