### ISSUE TITLE
Unable to retrive latest OMERO.java.zip

### ISSUE THREAD

**Issue by lldelisle** [ome/omero-py#367]
Dear developers,
I got an error when using the CLI for omero import because of this:
https://github.com/ome/omero-py/blob/c6880bad559b4b2a939771099db9c3b68455aadc/src/omero/plugins/import.py#L110
The error is:
```
Downloading https://downloads.openmicroscopy.org/omero/latest/OMERO.java.zip
Traceback (most recent call last):
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/bin/omero", line 10, in <module>
    sys.exit(main())
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/main.py", line 126, in main
    rv = omero.cli.argv()
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/cli.py", line 1787, in argv
    cli.invoke(args[1:])
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/cli.py", line 1225, in invoke
    stop = self.onecmd(line, previous_args)
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/cli.py", line 1302, in onecmd
    self.execute(line, previous_args)
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/cli.py", line 1384, in execute
    args.func(args)
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/plugins/import.py", line 552, in importer
    self.download_omero_java('latest')
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/site-packages/omero/plugins/import.py", line 588, in download_omero_java
    with ZipFile(BytesIO(resp.content)) as zipfile:
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/data/galaxy/galaxy/var/dependencies/_conda/envs/mulled-v1-db2fcfa8be636326417c50715ab9fec065adbfde66cca33b4958bee1dd8ad945/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
Indeed, seems that the url gives 404. When going to the download page, it seems that the url is: https://github.com/ome/openmicroscopy/releases/download/v5.6.6/OMERO.java-5.6.6-ice36.zip. Do you know if it is possible to fix the URL?
Thanks

**Comment by jburel** [comment]
I was realising new artifact this morning and a version bumped was missed.
The problem is now fixed

**Comment by lldelisle** [comment]
Thank you
