### ISSUE TITLE
Double cleanup in OMERO client

### ISSUE THREAD

**Issue by manics** [ome/omero-py#41]
Add some debugging to `src/omero/util/__init__.py`:
```diff
diff --git a/src/omero/util/__init__.py b/src/omero/util/__init__.py
index ae1994d54..b88ac257e 100644
--- a/src/omero/util/__init__.py
+++ b/src/omero/util/__init__.py
@@ -736,6 +736,9 @@ class Resources(object):

     @locked
     def cleanup(self):
+        import traceback
+        print('*** cleanup')
+        traceback.print_stack()
         self.stop_event.set()
         for m in self.stuff:
             self.safeClean(m)
```
Under Python 3 `cleanup` is called twice in the CLI:
```
$ omero login -s user@hostname -wpassword
Previously logged in to hostname:4064 as user
Created session for user@hostname:4064. Idle timeout: 10 min. Current group: read-only-1
*** cleanup
  File "/HOME/anaconda3/envs/tmp/bin/omero", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/HOME/work/omero-py/bin/omero", line 131, in <module>
    rv = omero.cli.argv()
  File "/HOME/work/omero-py/target/omero/cli.py", line 1732, in argv
    cli.invoke(args[1:])
  File "/HOME/work/omero-py/target/omero/cli.py", line 1191, in invoke
    self.close()
  File "/HOME/work/omero-py/target/omero/cli.py", line 1550, in close
    client.__del__()
  File "/HOME/work/omero-py/target/omero/clients.py", line 447, in __del__
    self.closeSession()
  File "/HOME/work/omero-py/target/omero/clients.py", line 1041, in closeSession
    self.stopKeepAlive()
  File "/HOME/work/omero-py/target/omero/clients.py", line 790, in stopKeepAlive
    self.__resources.cleanup()
  File "/HOME/work/omero-py/target/omero/util/decorators.py", line 91, in with_lock
    return func(*args, **kwargs)
  File "/HOME/work/omero-py/target/omero/util/__init__.py", line 741, in cleanup
    traceback.print_stack()
*** cleanup
  File "/HOME/work/omero-py/target/omero/util/__init__.py", line 757, in __del__
    self.cleanup()
  File "/HOME/work/omero-py/target/omero/util/decorators.py", line 91, in with_lock
    return func(*args, **kwargs)
  File "/HOME/work/omero-py/target/omero/util/__init__.py", line 741, in cleanup
    traceback.print_stack()
Exception ignored in: <bound method Resources.__del__ of <omero.util.Resources object at 0x111aeda58>>
Traceback (most recent call last):
  File "/HOME/work/omero-py/target/omero/util/__init__.py", line 757, in __del__
    self.cleanup()
  File "/HOME/work/omero-py/target/omero/util/decorators.py", line 91, in with_lock
    return func(*args, **kwargs)
  File "/HOME/work/omero-py/target/omero/util/__init__.py", line 743, in cleanup
    for m in self.stuff:
TypeError: 'NoneType' object is not iterable
```
Under Python 2 only the first `cleanup` is called as expected

**Comment by joshmoore** [comment]
This `cleanup` method is working for me locally:

```
    @locked
    def cleanup(self):
        stuff = self.stuff
        self.stuff = None
        self.stop_event.set()
        if stuff:
            for m in stuff:
                self.safeClean(m)
        self.logger.debug("Cleanup done")
```
